[package]
name = "rust_peg_solver"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_peg_solver"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
